--------------------------------------------------------
--  File created - Thursday-February-28-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS_LAT_LONG_CACHE
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."ADDRESS_LAT_LONG_CACHE" 
   (	"STREET" VARCHAR2(300 CHAR), 
	"CITY" VARCHAR2(75 CHAR), 
	"STATE" VARCHAR2(75 CHAR), 
	"ZIP" VARCHAR2(60 CHAR), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table CONGRESSIONAL_DB
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."CONGRESSIONAL_DB" 
   (	"COUNTER" NUMBER, 
	"HONORIFIC" VARCHAR2(30 CHAR), 
	"TITLE" VARCHAR2(30 CHAR), 
	"FULL_NAME" VARCHAR2(50 CHAR), 
	"LAST_NAME" VARCHAR2(30 CHAR), 
	"FIRST_NAME" VARCHAR2(30 CHAR), 
	"OFFICE_LOCATION" VARCHAR2(30 CHAR), 
	"ADDRESS" VARCHAR2(50 CHAR), 
	"ADDRESS2" VARCHAR2(50 CHAR), 
	"OFFICE_CITY" VARCHAR2(50 CHAR), 
	"STATE" VARCHAR2(30 CHAR), 
	"DISTRICT" VARCHAR2(4 CHAR), 
	"STATEDISTRICT" VARCHAR2(30 CHAR), 
	"DELETED" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"AUDIT_CREATED_BY" VARCHAR2(30 CHAR), 
	"AUDIT_CREATED_TIMESTAMP" DATE, 
	"AUDIT_MODIFIED_BY" VARCHAR2(30 CHAR), 
	"AUDIT_MODIFIED_TIMESTAMP" DATE, 
	"OFFICE_STATE" VARCHAR2(50 CHAR), 
	"OFFICE_ZIP" VARCHAR2(10 CHAR), 
	"SENTENCE_END" VARCHAR2(15 CHAR), 
	"HOUSE_SENATE" VARCHAR2(15 CHAR), 
	"CONGRESS" VARCHAR2(15 CHAR), 
	"POLITICAL_PARTY" VARCHAR2(20 CHAR), 
	"IMAGE_LOCATION" VARCHAR2(255 CHAR), 
	"PHONE_NUMBER" VARCHAR2(10 CHAR), 
	"WEBSITE_URL" VARCHAR2(255 CHAR), 
	"CONTACT_LINK" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONGRESSIONAL_DISTRICT
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."CONGRESSIONAL_DISTRICT" 
   (	"CONGRESSIONAL_DISTRICT_ID" NUMBER(10,0), 
	"USA_STATE_ID" NUMBER(10,0), 
	"CONGRESSIONAL_DISTRICT_NBR" NUMBER(3,0), 
	"LATITUDE_CENTER_NBR" NUMBER, 
	"LONGITUDE_CENTER_NBR" NUMBER, 
	"ZOOM_INITIAL_NBR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;

   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."CONGRESSIONAL_DISTRICT_ID" IS 'Unique ID for Congressional District';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."USA_STATE_ID" IS 'Foreign key column to USA_STATE table';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."CONGRESSIONAL_DISTRICT_NBR" IS 'Number which uniquely identifies the Congressional District within the USA State. ';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."LATITUDE_CENTER_NBR" IS 'Latitude of the center of the Congressional District';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."LONGITUDE_CENTER_NBR" IS 'Longitude of the center of the Congressional District';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT"."ZOOM_INITIAL_NBR" IS 'Initial Zoom Level for the Congressional District from Google Maps';
   COMMENT ON TABLE "WEB_MAPS"."CONGRESSIONAL_DISTRICT"  IS 'Stores Congressional District numbers for each USA state including latitude and longitude data';
--------------------------------------------------------
--  DDL for Table CONGRESSIONAL_DISTRICT_POLYGON
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON" 
   (	"CONG_DISTRICT_POLYGON_ID" NUMBER(10,0), 
	"CONGRESSIONAL_DISTRICT_ID" NUMBER(10,0), 
	"LATITUDE_POLYGON_POINT_NBR" NUMBER, 
	"LONGITUDE_POLYGON_POINT_NBR" NUMBER, 
	"SORT_SEQUENCE_NBR" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WEBMAP_DATA" ;

   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"."CONG_DISTRICT_POLYGON_ID" IS 'Unique ID for a Congressional District polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"."CONGRESSIONAL_DISTRICT_ID" IS 'Foreign key column to CONGRESSIONAL_DISTRICT table';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"."LATITUDE_POLYGON_POINT_NBR" IS 'Latitude value for a Congressional District polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"."LONGITUDE_POLYGON_POINT_NBR" IS 'Latitude value for a Congressional District polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"."SORT_SEQUENCE_NBR" IS 'Integer value for sorting Congressional District polygon points';
   COMMENT ON TABLE "WEB_MAPS"."CONGRESSIONAL_DISTRICT_POLYGON"  IS 'Stores points needed to draw a polygon representing Congressional District boundaries';
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_AUTH
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_AUTH" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"EXPORTER_STATE" VARCHAR2(75 BYTE), 
	"CNGRSNL_DSTRCT" VARCHAR2(15 BYTE), 
	"AMT_AUTH" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_AUTH_DEV
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_AUTH_DEV" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"EXPORTER_STATE" VARCHAR2(75 BYTE), 
	"CNGRSNL_DSTRCT" VARCHAR2(15 BYTE), 
	"AMT_AUTH" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_AUTH_TEST
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_AUTH_TEST" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"EXPORTER_STATE" VARCHAR2(75 BYTE), 
	"CNGRSNL_DSTRCT" VARCHAR2(15 BYTE), 
	"AMT_AUTH" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_DTL
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_DTL" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"CNGRSNL_DSTRCT" VARCHAR2(15 CHAR), 
	"EXPORTER_CITY" VARCHAR2(75 CHAR), 
	"EXPORTER_STATE" VARCHAR2(75 CHAR), 
	"EXPORTER_COUNTY" VARCHAR2(75 CHAR), 
	"PROGRAM" VARCHAR2(75 CHAR), 
	"EXPORTER_NAME" VARCHAR2(75 CHAR), 
	"TERM" VARCHAR2(15 CHAR), 
	"DEAL_NUMBER" VARCHAR2(15 CHAR), 
	"SUPPORTED_DT" DATE, 
	"FLAG_SB" VARCHAR2(3 CHAR), 
	"FLAG_MO" VARCHAR2(3 CHAR), 
	"FLAG_WO" VARCHAR2(3 CHAR), 
	"FLAG_ENV" VARCHAR2(3 CHAR), 
	"FLAG_RE" VARCHAR2(3 CHAR), 
	"EXPORTER_NAICS_DESC" VARCHAR2(100 CHAR), 
	"WO_SUPPORTED" NUMBER, 
	"MO_SUPPORTED" NUMBER, 
	"RE_SUPPORTED" NUMBER, 
	"EB_SUPPORTED" NUMBER, 
	"SB_SUPPORTED" NUMBER, 
	"AMT_SUPPORTED" NUMBER(21,2), 
	"EXPORTER_NAICS_LVL2_DESC" VARCHAR2(75 CHAR), 
	"EXPORT_DESTINATION" VARCHAR2(75 CHAR), 
	"POLICY_TYPE" VARCHAR2(75 CHAR), 
	"EXPORTER_CHARACTERISTICS" VARCHAR2(150 CHAR), 
	"SUPPORTED_DT_YR_MO" VARCHAR2(150 CHAR), 
	"AMT_EXPORT_SUPPORTED" NUMBER(22,2), 
	"NUM_JOBS_SUPPORTED" NUMBER(22,10), 
	"EXPORTER_ADDRESS_LINE_1" VARCHAR2(300 CHAR), 
	"EXPORTER_ADDRESS_LINE_2" VARCHAR2(300 CHAR), 
	"EXPORTER_ADDRESS_LINE_3" VARCHAR2(300 CHAR), 
	"EXPORTER_ZIP_CODE" VARCHAR2(60 CHAR), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_SMRY
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_SMRY" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"WO_SUPPORTED" NUMBER, 
	"MO_SUPPORTED" NUMBER, 
	"RE_SUPPORTED" NUMBER, 
	"EB_SUPPORTED" NUMBER, 
	"SB_SUPPORTED" NUMBER, 
	"AMT_SUPPORTED" NUMBER(21,2), 
	"AMT_EXPORT_SUPPORTED" NUMBER(22,2), 
	"NUM_JOBS_SUPPORTED" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_SMRY_DEV
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_SMRY_DEV" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"WO_SUPPORTED" NUMBER, 
	"MO_SUPPORTED" NUMBER, 
	"RE_SUPPORTED" NUMBER, 
	"EB_SUPPORTED" NUMBER, 
	"SB_SUPPORTED" NUMBER, 
	"AMT_SUPPORTED" NUMBER(21,2), 
	"AMT_EXPORT_SUPPORTED" NUMBER(22,2), 
	"NUM_JOBS_SUPPORTED" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table MAP_CONG_DIST_SMRY_TEST
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."MAP_CONG_DIST_SMRY_TEST" 
   (	"DT_YR_FSCL" NUMBER(38,0), 
	"WO_SUPPORTED" NUMBER, 
	"MO_SUPPORTED" NUMBER, 
	"RE_SUPPORTED" NUMBER, 
	"EB_SUPPORTED" NUMBER, 
	"SB_SUPPORTED" NUMBER, 
	"AMT_SUPPORTED" NUMBER(21,2), 
	"AMT_EXPORT_SUPPORTED" NUMBER(22,2), 
	"NUM_JOBS_SUPPORTED" NUMBER(22,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;
--------------------------------------------------------
--  DDL for Table TOAD_PLAN_TABLE
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."TOAD_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30 BYTE), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"OPERATION" VARCHAR2(30 BYTE), 
	"OPTIONS" VARCHAR2(255 BYTE), 
	"OBJECT_NODE" VARCHAR2(128 BYTE), 
	"OBJECT_OWNER" VARCHAR2(30 BYTE), 
	"OBJECT_NAME" VARCHAR2(30 BYTE), 
	"OBJECT_ALIAS" VARCHAR2(65 BYTE), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(30 BYTE), 
	"OPTIMIZER" VARCHAR2(255 BYTE), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255 BYTE), 
	"PARTITION_START" VARCHAR2(255 BYTE), 
	"PARTITION_STOP" VARCHAR2(255 BYTE), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30 BYTE), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
	"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
	"PROJECTION" VARCHAR2(4000 BYTE), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(30 BYTE), 
	"OTHER_XML" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" 
 LOB ("OTHER_XML") STORE AS BASICFILE (
  TABLESPACE "WEBMAP_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USA_STATE
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."USA_STATE" 
   (	"USA_STATE_ID" NUMBER(10,0), 
	"NAME_TXT" VARCHAR2(50 BYTE), 
	"ABBREVIATION_TXT" VARCHAR2(50 BYTE), 
	"LATITUDE_CENTER_NBR" NUMBER, 
	"LONGITUDE_CENTER_NBR" NUMBER, 
	"ZOOM_INITIAL_NBR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEBMAP_DATA" ;

   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."USA_STATE_ID" IS 'Unique ID for a USA State';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."NAME_TXT" IS 'Full USA State Name';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."ABBREVIATION_TXT" IS 'Abbreviation for the full USA State Name';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."LATITUDE_CENTER_NBR" IS 'Latitude of the center of the State';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."LONGITUDE_CENTER_NBR" IS 'Longitude of the center of the State';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE"."ZOOM_INITIAL_NBR" IS 'Initial Zoom Level for the State from Google Maps';
   COMMENT ON TABLE "WEB_MAPS"."USA_STATE"  IS 'Stores USA State information including latitude and longitude data';
--------------------------------------------------------
--  DDL for Table USA_STATE_POLYGON
--------------------------------------------------------

  CREATE TABLE "WEB_MAPS"."USA_STATE_POLYGON" 
   (	"USA_STATE_POLYGON_ID" NUMBER(10,0), 
	"USA_STATE_ID" NUMBER(10,0), 
	"LATITUDE_POLYGON_POINT_NBR" NUMBER, 
	"LONGITUDE_POLYGON_POINT_NBR" NUMBER, 
	"SORT_SEQUENCE_NBR" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "WEBMAP_DATA" ;

   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE_POLYGON"."USA_STATE_POLYGON_ID" IS 'Unique ID for a USA State polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE_POLYGON"."USA_STATE_ID" IS 'Foreign key column to USA_STATE table';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE_POLYGON"."LATITUDE_POLYGON_POINT_NBR" IS 'Latitude value for a USA state polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE_POLYGON"."LONGITUDE_POLYGON_POINT_NBR" IS 'Longitude value for a USA state polygon point';
   COMMENT ON COLUMN "WEB_MAPS"."USA_STATE_POLYGON"."SORT_SEQUENCE_NBR" IS 'Integer value for sorting USA State polygon points';
   COMMENT ON TABLE "WEB_MAPS"."USA_STATE_POLYGON"  IS 'Stores points needed to draw a polygon representing USA state boundaries';
