truncate table waia.authority_types;
truncate table waia.groups;
truncate table waia.contact_role_types;

INSERT INTO waia.authority_types (description, created_by, created_date, updated_by, updated_date) VALUES("Read Only", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.authority_types (description, created_by, created_date, updated_by, updated_date) VALUES("Contributor", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.authority_types (description, created_by, created_date, updated_by, updated_date) VALUES("Admin", "tom.edwards", now(), "tom.edwards", now());

INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Archives", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Executive Committee", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("H&I", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Literature", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("New Reporter", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Nightwatch", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Outreach", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Public Information", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Registrar", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Rules", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Secretary", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Special Needs", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Staff", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Treasurer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.groups (group_name, created_by, created_date, updated_by, updated_date) VALUES("Vice Chairperson", "tom.edwards", now(), "tom.edwards", now());

INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Alternate WAIA Representative", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Archives", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Co-Treasurer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("CPC", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Electronic New Reporter Subscriber", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Executive Committee", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("H&I Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("H&I DC Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("H&I MC Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("H&I Member", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("H&I PG Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Literature", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("New Reporter", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Nightwatch", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Nightwatch Volunteer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Outreach", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Paper New Reporter Subscriber", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Phone Volunteer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Public Information", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Registrar", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Rules", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Secretary", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Special Needs", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Staff", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Treasurer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Treasurer", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("Vice Chairperson", "tom.edwards", now(), "tom.edwards", now());
INSERT INTO waia.contact_role_types (description, created_by, created_date, updated_by, updated_date) VALUES("WAIA Representative", "tom.edwards", now(), "tom.edwards", now());